# group_vars/all/cis_profile.yml
# =============================================================================
# CIS Compliance Profile
# =============================================================================
---
rhel10_cis_profile:
  base_profile: xccdf_org.ssgproject.content_profile_cis_server_l1
  content_path: /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
  tailoring_path: /etc/openscap/qbe-cis-l1-tailoring.xml
  tailoring_id: "xccdf_qbe.com_tailoring_cis-l1-rhel10"
  benchmark_id: "xccdf_org.ssgproject.content_benchmark_RHEL-10"
  minimum_score: 95.0

 # JSON tailoring — used by Image Builder at build time
  json_tailoring_profile_id: "cis_server_l1_tailored"
  json_tailoring_filepath: "/etc/openscap/qbe-cis-l1-tailoring.json"
